version: '3.8'

services:
  comictagger-watcher:
    image: iceburn1/comictagger-watcher:latest
    container_name: comictagger-watcher
    restart: unless-stopped
    
    # Environment variables
    environment:
      # Required: Directory to watch for comics
      - WATCHED_DIR=/watched_dir
      
      # Optional: Directory for duplicate files
      - DUPLICATE_DIR=/duplicates
      
      # Optional: Custom user/group IDs for file permissions (recommended)
      # Use your host user ID: run `id -u` and `id -g` on Linux/macOS
      - PUID=99
      - PGID=100
      
      # Optional: Web interface port (default: 5000)
      - WEB_PORT=5000
      
      # Optional: Enable HTTPS (default: false)
      # - HTTPS_ENABLED=true
      # - SSL_CERT=/ssl/cert.pem
      # - SSL_KEY=/ssl/key.pem
      
      # Optional: Number of Gunicorn workers (default: 2)
      - GUNICORN_WORKERS=2
      
      # Optional: Number of concurrent processing threads (default: 4)
      - MAX_WORKERS=4
      
      # Optional: SQLite database cache size in MB (default: 64)
      # Increase for large libraries (128-256MB), decrease for small libraries (32MB)
      - DB_CACHE_SIZE_MB=64
      
      # Optional: Log file size limit in bytes (default: 5242880 = 5MB)
      - LOG_MAX_BYTES=5242880
      
      # Optional: Enable debug logging (default: false)
      # - DEBUG_MODE=true
      
      # Optional: GitHub integration for automatic issue creation on errors
      # - GITHUB_TOKEN=your_github_token_here
      # - GITHUB_REPOSITORY=mleenorris/ComicMaintainer
      # - GITHUB_ISSUE_ASSIGNEE=your_username
    
    # Volumes
    volumes:
      # Required: Mount your comics directory
      - /path/to/your/comics:/watched_dir
      
      # Required: Mount config directory for persistent data
      - /path/to/your/config:/Config
      
      # Optional: Mount duplicates directory
      - /path/to/your/duplicates:/duplicates
      
      # Optional: Mount SSL certificates directory for HTTPS
      # - /path/to/your/ssl:/ssl:ro
    
    # Ports
    ports:
      - "5000:5000"
      # Use port 443 for HTTPS if enabled
      # - "443:5000"
    
    # Health check
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --quiet --tries=1 --spider $$([ \"$$HTTPS_ENABLED\" = \"true\" ] && echo \"https\" || echo \"http\")://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Labels for organization
    labels:
      - "com.example.description=ComicTagger Watcher Service"
      - "com.example.version=1.0.0"
