name: Cleanup Copilot Branches

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-branch:
    # Only run for branches that start with "copilot/"
    if: startsWith(github.head_ref, 'copilot/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Delete copilot branch
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "PR #${{ github.event.pull_request.number }} was closed"
          echo "Branch: $BRANCH_NAME"
          
          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            echo "PR was merged - deleting branch $BRANCH_NAME"
          else
            echo "PR was closed without merging - deleting branch $BRANCH_NAME"
          fi
          
          # Delete the branch using GitHub API
          curl -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME"
          
          echo "Branch $BRANCH_NAME deleted successfully"
